---
name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - run: poe lint
      - run: poe format-check

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - run: poe test-unit

  e2e:
    needs: test
    runs-on: ubuntu-latest
    env:
      COMPOSE: "docker compose"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - run: poe e2e
