---
name: E2E

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      COMPOSE: "docker compose"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - run: poe e2e
